Use the right type on Response for tests
trallnag/prometheus-fastapi-instrumentator pull request #139
Opened 2022-05-26 05:52 UTC by Kludex

2022-05-26 05:52 UTC, Kludex commented on tests/test_instrumentation.py
>      assert b"# HELP process_cpu_seconds_total" in response.content
This line of code doesn't pass locally... Which is incredibly annoying.

2022-06-06 09:14 UTC, trallnag commented
Hey @Kludex, thanks for your contribution efforts. Generally I'm open towards switching to a pure ASGI implementation. But sadly I can't support you with the implementation because I lack knowledge regarding ASGI and async Python in general. Can you tell me what the advantage of switching to an ASGI implementation?

2022-06-06 10:31 UTC, trallnag commented
Some tests are failing. It seems like something about the way paths / handlers are exposed has changed. For example this test is failing. I think it is due to the instrumentator not passing all parameters to the middleware. Looking at `excluded_handlers`

2022-06-11 23:23 UTC, adriangb requested changes

2022-06-11 23:23 UTC, adriangb commented on prometheus_fastapi_instrumentator/instrumentation.py
> +            instrumentations=self.instrumentations,
```suggestion
            instrumentations=self.instrumentations,
            excluded_handlers=self.excluded_handlers,
```

This fixes the tests it seems

2022-06-11 23:25 UTC, adriangb commented
> Can you tell me what the advantage of switching to an ASGI implementation?

`BaseHTTPMiddleware` (which is what `app.middleware` uses) is a wrapper around generic ASGI middleware to expose a request/response interface. Internally it is _very_ complex, and has several bugs which we don't think can ever be resolved. Because of this, we discourage its use. You can read more here: https://www.starlette.io/middleware/#basehttpmiddleware

Unrelated this this PR: just FYI I couldn't get tests to run on an M1 Mac, I had to run them in a Docker container.

2022-06-12 17:48 UTC, merged

2022-06-12 20:12 UTC, Kludex commented
Thanks 👍

2022-06-13 11:32 UTC, Kludex commented
I didn't notice the title was wrong 😅

2022-06-13 13:11 UTC, tiangolo commented
Niceee! Thanks for this! 🙇