Feature to add custom labels with metrics
trallnag/prometheus-fastapi-instrumentator pull request #287
Opened 2024-02-26 08:58 UTC by martian711

* Added feature to add custom labels like service name with metrics
* Custom labels help to make query based on custom labels on prometheus dashboard
* Its same as we use `default_labels` in https://pypi.org/project/prometheus-flask-exporter/

Changes are welcome, please suggest if any.

2024-03-12 21:02 UTC, trallnag requested changes

2024-03-12 21:02 UTC, trallnag commented on src/prometheus_fastapi_instrumentator/metrics.py
> +        custom_labels: dict,
I prefer to not have this attribute in the `Info` class. It should only contain attributes that are relevant for the respective request / response pair.

It is sufficient if all metrics closures included with this package get it as an additional parameter.

2024-03-12 21:03 UTC, trallnag commented
In general I would be fine with merging this if requested changes are implemented

2025-02-21 12:49 UTC, Budlee commented
Hey @trallnag,

I can pick this one up as it seems to have been left but a feature I would like.
Is your only request that the custom_labels are removed from the Info class?

2025-03-04 10:43 UTC, jpizquierdo commented
I am really interested in this one... for my use case I need to specify namescape and pod as labels 😀 . @Budlee are you followikg with this one??
@martian711 did you abandon this one??
@trallnag I can offer help here also..

2025-03-04 11:58 UTC, Budlee commented
@jpizquierdo, I've not started making the change. I was waiting to hear from @trallnag if anything else was required apart from the removal of the labels from the info class.

2025-03-04 12:01 UTC, trallnag commented
I'll give it a look this evening 








---- Am Tue, 04 Mar 2025 12:58:28 +0100 ***@***.*** schrieb ----


Budlee
 left a comment 
(trallnag/prometheus-fastapi-instrumentator#287)

@jpizquierdo, I've not started making the change. I was waiting to hear from @trallnag if anything else was required apart from the removal of the labels from the info class.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.

2025-03-04 20:34 UTC, trallnag commented
@Budlee, if you make the change I will merge it and release a new version.

You could also add a test for this in `test_metrics.py` after line 597, something like `test_default_custom_labels`. No need to add one for every single closure

2025-03-05 20:14 UTC, Budlee commented
Working on it now

2025-03-05 20:41 UTC, Budlee commented
PR is now available at: https://github.com/trallnag/prometheus-fastapi-instrumentator/pull/326

2025-03-19 19:40 UTC, trallnag commented
Implemented in #326. Released in Thanks for the patience. Released in <https://github.com/trallnag/prometheus-fastapi-instrumentator/releases/tag/v7.1.0>.

2025-03-19 19:40 UTC, closed without merging